image: docker:latest

services:
    - docker:dind

before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker login -u $HUB_USER -p $HUB_PASSWORD 

build:
    script:
        - docker build -t $CI_REGISTRY/$CI_PROJECT_PATH/ikiwiki .
        - docker push $CI_REGISTRY/$CI_PROJECT_PATH/ikiwiki
        - docker tag $CI_REGISTRY/$CI_PROJECT_PATH/ikiwiki $HUB_USER/ikiwiki
        - docker push $HUB_USER/ikiwiki

